heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://192.168.0.82:8080
    - http://192.168.0.82:8081
    - http://192.168.0.82:8082
    - http://192.168.0.82:8083
    - http://192.168.0.82:8084
    - http://192.168.0.82:8085
    - http://192.168.0.82:8086
    - http://192.168.0.82:8087
    - http://192.168.0.82:8088
    - http://192.168.0.82:8089

processors:
- add_cloud_metadata: ~

#output.elasticsearch:
#  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
